name: Veri Senkronizasyonu

on:
  workflow_dispatch:
  schedule:
    - cron: '45 8 * * 1-5' # Her iş günü Türkiye saati ile 11:45

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: OtoFonWeb Deposunu Kopyala
        uses: actions/checkout@v3

      - name: Özel OtoFon Deposundan Veriyi Çek
        run: |
          # ACCESS_TOKEN sırrını kullanarak özel depoyu klonla
          git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/HicabiAlptekin/OtoFon.git private_repo

      - name: Debug - Klonlanan Depodaki Dosyaları Listele
        run: |
          echo "Klonlanan 'private_repo' klasörünün içeriği:"
          ls -R private_repo

      - name: Veri Dosyasını Kopyala
        run: |
          # Veri dosyasını ana dizine kopyala
          cp private_repo/Fon_Verileri.csv .

      - name: Veri Dosyasını Güncelle ve Commit At
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Veri dosyası otomatik olarak güncellendi"
          file_pattern: "Fon_Verileri.csv"
